// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjzwroidjwmvhqfhzhuu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqendyb2lkandtdmhxZmh6aHV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzMzgxNDUsImV4cCI6MjA1MzkxNDE0NX0.iwUaMH_GS0nPHCi8xPso5R_bwjxw5B_HSijokW2usA8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);